
"""
Hierarchical JSON Builder — Method 2
======================================
Reads the *_markdown_bbox.json produced by nemotron_parse_pipeline.py,
builds a hierarchical structure matching the reference schema exactly,
and calls a local Ollama model to generate summaries.

Reference schema (per node):
  {
    "title":       string,
    "node_id":     "0000",          ← zero-padded 4-digit counter
    "start_index": int,             ← first page this section appears on
    "end_index":   int,             ← last page this section spans
    "summary":     string,          ← generated by Ollama
    "nodes": [ ... ]                ← child nodes (only present if non-empty)
  }

Top-level output:
  {
    "doc_name":  "filename.pdf",
    "structure": [ <top-level nodes> ]
  }

The _structure.json is saved inside the same doc folder it came from:
  output/
  ├── Adaptive Platform Machine Configuration/
  │   ├── Adaptive Platform Machine Configuration_markdown_bbox.json   ← input
  │   ├── Adaptive Platform Machine Configuration_structure.json       ← output
  │   └── ...
  └── Explanation of Sensor Interfaces/
      ├── Explanation of Sensor Interfaces_markdown_bbox.json          ← input
      ├── Explanation of Sensor Interfaces_structure.json              ← output
      └── ...

Usage:

  # Single file
  python build_hierarchy.py --input output/MyDoc/MyDoc_markdown_bbox.json

  # Entire results directory (auto-finds all *_markdown_bbox.json files)
  python build_hierarchy.py --results_dir output/

  # Custom Ollama model / host
  python build_hierarchy.py --results_dir output/ --ollama_model llama3

  # Skip summaries (tree structure only, fast for testing)
  python build_hierarchy.py --results_dir output/ --no_summary

Requirements:
  pip install requests
  Ollama running locally: https://ollama.com
  Pull a model first:  ollama pull mistral   (or llama3, phi3, gemma, etc.)
"""

import json
import re
import sys
import argparse
import requests
from pathlib import Path
from typing import Optional

# ─── Ollama defaults ──────────────────────────────────────────────────────────
DEFAULT_OLLAMA_HOST  = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "qwen3:latest"

# ─── Nemotron element type sets ───────────────────────────────────────────────
HEADING_TYPES = {"Title", "Section-header"}
BODY_TYPES    = {"Text", "List-item", "Caption", "Table", "Footnote"}


# ══════════════════════════════════════════════════════════════════════════════
# 1.  HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def _heading_depth(element: dict) -> int:
    """
    Return heading depth (0 = top-level, 1 = sub, 2 = sub-sub …) or -1 if
    the element is not a heading.

    Priority order:
      1. Filter — skip '## Page N' markers added by our pipeline → return -1
      2. Filter — skip TOC entries (text contains '.....' page-ref pattern) → -1
      3. Filter — skip constraint/spec labels like [AP_TPS_...] or [constr_...] → -1
      4. Filter — skip body sentences: text starting with a capital letter
                  followed by a lowercase word (not a section number pattern) → -1
      5. Nemotron type == "Title"  → depth 0
      6. Section number dot-count — the ONLY reliable depth signal:
           '1 Introduction'   → depth 0  (1 numeric part, 0 dots)
           '1.1 Sub'          → depth 1  (2 parts, 1 dot)
           '2.4.2 Detail'     → depth 2  (3 parts, 2 dots)
           'A Reference'      → depth 0  (appendix, single letter)
           'A.1 Terms'        → depth 1  (appendix sub)
         Section numbers MUST start at the very beginning of the text (after
         stripping '#') and be followed by a short title word, NOT by '.....'
      7. Markdown '#' prefix count → fallback for genuinely marked headings
    """
    elem_type = element.get("type", "")
    text      = element.get("text", "").lstrip()

    # ── 1. Filter "## Page N" markers ────────────────────────────────────────
    if re.match(r'^#{1,6}\s*Page\s+\d+\s*$', text, re.IGNORECASE):
        return -1

    # Strip markdown '#' prefix for all subsequent checks
    clean = re.sub(r'^#{1,6}\s*', '', text).strip()

    # ── 2. Filter TOC entries — they contain '.....' or ' ..... ' ────────────
    if '.....' in clean or re.search(r'\s\.{3,}\s*\d+\s*$', clean):
        return -1

    # ── 3. Filter constraint / spec labels — [AP_TPS_...], [constr_...] ──────
    if re.match(r'^\[', clean):
        return -1

    # ── 4. Filter body sentences starting with capital + lowercase word ───────
    # A real section heading looks like "2 Intro" or "A Reference" (short, ALL-CAPS
    # or Title-case single/few words).  A body sentence looks like "A rough criterion
    # for identifying..." — capital letter then immediately a lowercase continuation.
    # We only want to match single capital letters that are appendix labels (A, B, C)
    # followed by a dot+number or a short title (no lowercase after first word).
    body_sentence = re.match(r'^[A-Z][a-z]', clean)   # "A rough...", "The purpose..."
    if body_sentence:
        # Only allow if it is a single-letter appendix label like "A Reference"
        # which means: one capital letter, then space, then one or more Title-case words
        appendix = re.match(r'^([A-Z])\s+([A-Z][^\s].*)', clean)
        if not appendix:
            return -1

    # ── 5. Nemotron Title type → always top-level ────────────────────────────
    if elem_type == "Title":
        return 0

    # ── 6. Section number dot-count ──────────────────────────────────────────
    # Strict: number/letter + optional .N.N + space + at least one non-space char
    # Must NOT be followed by '.....' (already filtered above, but double-safe)
    sec_match = re.match(
        r'^([A-Z]|\d+)((\.\d+)+)?\s+\S',
        clean
    )
    if sec_match:
        dots_part = sec_match.group(2) or ""
        return dots_part.count(".")

    # ── 7. Markdown '#' prefix fallback ──────────────────────────────────────
    hash_match = re.match(r'^(#{1,6})\s', text)
    if hash_match:
        return len(hash_match.group(1)) - 1

    return -1


def _clean_title(text: str) -> str:
    """Strip only markdown '#' markers. Section numbers are kept as-is."""
    return re.sub(r'^#{1,6}\s*', '', text).strip()


def _is_page_marker(text: str) -> bool:
    """Return True if this is a '## Page N' marker inserted by our pipeline."""
    return bool(re.match(r'^#{1,6}\s*Page\s+\d+\s*$', text.strip(), re.IGNORECASE))


def _next_node_id(counter: list) -> str:
    """Return zero-padded 4-digit node ID and increment the counter."""
    nid = f"{counter[0]:04d}"
    counter[0] += 1
    return nid


# ══════════════════════════════════════════════════════════════════════════════
# 2.  OLLAMA
# ══════════════════════════════════════════════════════════════════════════════

def _check_ollama(host: str, model: str) -> bool:
    """Return True if Ollama is reachable and the requested model is available."""
    try:
        resp = requests.get(f"{host}/api/tags", timeout=5)
        resp.raise_for_status()
        available = [m["name"].split(":")[0]
                     for m in resp.json().get("models", [])]
        if model.split(":")[0] not in available:
            print(f"  [WARN] Model '{model}' not found in Ollama.")
            print(f"         Available: {available}")
            print(f"         Run:  ollama pull {model}")
            return False
        return True
    except Exception as e:
        print(f"  [WARN] Cannot reach Ollama at {host}: {e}")
        return False


def _summarise(text: str, title: str, host: str, model: str) -> str:
    """
    Call Ollama to summarise `text` under heading `title`.
    Falls back to a 500-char truncation of raw text on any error.
    """
    if not text.strip():
        return ""

    prompt = (
        f"You are a technical documentation assistant.\n"
        f"Summarize the following section titled \"{title}\" in 3-5 sentences.\n"
        f"Be precise, preserve all technical details, and do not add information "
        f"that is not present in the text.\n\n"
        f"---\n{text[:4000]}\n---\n\n"
        f"Summary:"
    )
    payload = {
        "model":   model,
        "prompt":  prompt,
        "stream":  False,
        "options": {"temperature": 0.2, "num_predict": 400},
    }
    try:
        resp = requests.post(f"{host}/api/generate",
                             json=payload, timeout=120)
        resp.raise_for_status()
        return resp.json().get("response", "").strip()
    except Exception as e:
        print(f"      [!] Ollama error for '{title}': {e}")
        return text[:500].strip() + ("…" if len(text) > 500 else "")


# ══════════════════════════════════════════════════════════════════════════════
# 3.  FLAT LIST → HIERARCHICAL TREE
# ══════════════════════════════════════════════════════════════════════════════

def _build_tree(flat_elements: list, counter: list,
                ollama_host: str, ollama_model: str,
                use_summary: bool, ollama_ok: bool) -> list:
    """
    Convert a flat Nemotron element list into a nested node tree.

    Algorithm:
      - Walk elements in reading order (Nemotron already returns them this way)
      - Heading  → create node, push onto ancestor stack at correct depth
      - Body     → accumulate raw text under current heading
      - When a heading at same/higher level is encountered → flush summary for
        the outgoing node, pop stack, attach new node to correct parent
    """
    stack = []   # each entry: { "node": dict, "depth": int, "raw_text": list }
    roots = []   # depth-0 nodes

    # ── inner helpers ─────────────────────────────────────────────────────────

    def _flush(entry: dict):
        """Generate summary (or truncate) for a completed node."""
        node  = entry["node"]
        raw   = "\n".join(entry["raw_text"])
        title = node["title"]

        if not use_summary:
            node["summary"] = ""
            return

        if ollama_ok:
            print(f"        [Ollama] {title[:70]}")
            node["summary"] = _summarise(raw, title, ollama_host, ollama_model)
        else:
            node["summary"] = (raw[:500].strip() +
                               ("…" if len(raw) > 500 else ""))

    def _attach(node: dict, depth: int):
        """Pop stack to correct level, then attach node to its parent."""
        while stack and stack[-1]["depth"] >= depth:
            _flush(stack[-1])
            stack.pop()

        if not stack:
            roots.append(node)
        else:
            stack[-1]["node"].setdefault("nodes", []).append(node)

    # ── main walk ─────────────────────────────────────────────────────────────

    for element in flat_elements:
        elem_type = element.get("type", "")
        text      = element.get("text", "").strip()
        page      = element.get("page", 1)

        if not text:
            continue
        if elem_type in ("Page-header", "Page-footer"):
            continue
        if _is_page_marker(text):
            continue

        depth = _heading_depth(element)

        if depth >= 0:
            # ── Heading: create node ─────────────────────────────────────────
            node = {
                "title":       _clean_title(text),
                "node_id":     _next_node_id(counter),
                "start_index": page,
                "end_index":   page,
                "summary":     "",
            }
            _attach(node, depth)
            stack.append({"node": node, "depth": depth, "raw_text": []})

        elif elem_type in BODY_TYPES and text and stack:
            # ── Body: accumulate under current heading ───────────────────────
            stack[-1]["raw_text"].append(text)
            if page > stack[-1]["node"]["end_index"]:
                stack[-1]["node"]["end_index"] = page

    # Flush any remaining stack entries
    while stack:
        _flush(stack[-1])
        stack.pop()

    return roots


def _propagate_end_index(nodes: list):
    """
    Walk the tree bottom-up so each parent's end_index reflects
    the deepest page reached by any of its descendants.
    """
    for node in nodes:
        children = node.get("nodes", [])
        if children:
            _propagate_end_index(children)
            deepest = max(c["end_index"] for c in children)
            if deepest > node["end_index"]:
                node["end_index"] = deepest


def _drop_empty_nodes_key(nodes: list):
    """
    Remove the 'nodes' key entirely from leaf nodes so the output
    matches the reference schema (leaves have no 'nodes' key at all).
    """
    for node in nodes:
        children = node.get("nodes", [])
        if children:
            _drop_empty_nodes_key(children)
        else:
            node.pop("nodes", None)


# ══════════════════════════════════════════════════════════════════════════════
# 4.  LOAD markdown_bbox JSON
# ══════════════════════════════════════════════════════════════════════════════

def load_markdown_bbox_json(json_path: Path) -> tuple:
    """
    Load a *_markdown_bbox.json file from nemotron_parse_pipeline.py.
    Returns (doc_name: str, flat_elements: list).
    Raises ValueError with a clear message on bad input.
    """
    if not json_path.exists():
        raise FileNotFoundError(f"File not found: {json_path}")

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if "pages" not in data:
        raise ValueError(
            f"'{json_path.name}' has no 'pages' key — "
            "make sure you are passing a *_markdown_bbox.json file."
        )

    doc_name      = data.get("doc_name", json_path.stem)
    flat_elements = []

    for page_entry in data.get("pages", []):
        page_num = page_entry.get("page", 0)
        result   = page_entry.get("result")

        if result is None:
            continue

        if isinstance(result, list):
            for elem in result:
                e = dict(elem)
                e["page"] = page_num
                flat_elements.append(e)

        elif isinstance(result, dict) and "text" in result:
            # markdown_no_bbox slipped in — treat as plain text block
            flat_elements.append({
                "type": "Text",
                "text": result["text"],
                "page": page_num,
            })

    return doc_name, flat_elements


# ══════════════════════════════════════════════════════════════════════════════
# 5.  DISCOVER  *_markdown_bbox.json  FILES IN A RESULTS DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

def discover_bbox_files(results_dir: str) -> list:
    """
    Walk `results_dir` and return a sorted list of all
    *_markdown_bbox.json files found in any immediate sub-folder.

    Expected layout:
      results_dir/
      ├── Doc A/
      │   └── Doc A_markdown_bbox.json   ← found
      └── Doc B/
          └── Doc B_markdown_bbox.json   ← found
    """
    root = Path(results_dir)
    if not root.is_dir():
        print(f"[ERROR] Not a valid directory: {results_dir}")
        sys.exit(1)

    # Search only one level deep: results_dir/<doc_folder>/*_markdown_bbox.json
    # This avoids picking up pages/page_001_markdown_bbox.json etc.
    found = sorted(root.glob("*/*_markdown_bbox.json"))

    if not found:
        print(f"[ERROR] No *_markdown_bbox.json files found under: {results_dir}")
        sys.exit(1)

    return found


# ══════════════════════════════════════════════════════════════════════════════
# 6.  PROCESS ONE FILE
# ══════════════════════════════════════════════════════════════════════════════

def process_one(json_path: Path,
                output_dir: Optional[Path],
                ollama_host: str,
                ollama_model: str,
                use_summary: bool,
                ollama_ok: bool) -> bool:
    """
    Build hierarchy for a single *_markdown_bbox.json file.
    Returns True on success, False on failure.
    """
    try:
        print(f"\n  [→] Loading : {json_path.name}")
        doc_name, flat_elements = load_markdown_bbox_json(json_path)

        if not flat_elements:
            print(f"  [WARN] No elements found — skipping {json_path.name}")
            return False

        print(f"  [✓] Elements: {len(flat_elements)} | Doc: {doc_name}")
        print(f"  [→] Building hierarchy tree …")

        counter   = [0]
        structure = _build_tree(
            flat_elements,
            counter      = counter,
            ollama_host  = ollama_host,
            ollama_model = ollama_model,
            use_summary  = use_summary,
            ollama_ok    = ollama_ok,
        )

        _propagate_end_index(structure)
        _drop_empty_nodes_key(structure)

        total_nodes = counter[0]
        print(f"  [✓] Tree built — {total_nodes} nodes")

        # Assemble output
        output = {"doc_name": doc_name, "structure": structure}

        # Output path: same folder as input (or custom output_dir)
        save_dir = output_dir if output_dir else json_path.parent
        save_dir.mkdir(parents=True, exist_ok=True)

        # Filename: strip _markdown_bbox → add _structure
        stem     = json_path.stem.replace("_markdown_bbox", "")
        out_path = save_dir / f"{stem}_structure.json"

        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(output, f, ensure_ascii=False, indent=2)

        print(f"  [✓] Saved   : {out_path}")
        return True

    except (FileNotFoundError, ValueError) as e:
        print(f"  [ERROR] {e}")
        return False
    except Exception as e:
        print(f"  [ERROR] Unexpected error processing {json_path.name}: {e}")
        return False


# ══════════════════════════════════════════════════════════════════════════════
# 7.  ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=(
            "Build hierarchical _structure.json from Nemotron markdown_bbox output.\n"
            "Works on a single file (--input) or an entire results directory (--results_dir)."
        ),
        formatter_class=argparse.RawTextHelpFormatter,
        epilog="""
examples:
  # Single file
  python build_hierarchy.py --input output/MyDoc/MyDoc_markdown_bbox.json

  # Entire results directory — auto-finds every *_markdown_bbox.json
  python build_hierarchy.py --results_dir output/

  # Different Ollama model
  python build_hierarchy.py --results_dir output/ --ollama_model llama3

  # Save all structure files to a separate folder instead of doc sub-folders
  python build_hierarchy.py --results_dir output/ --output_dir ./structure_outputs

  # Skip summaries (fast, for testing tree structure only)
  python build_hierarchy.py --results_dir output/ --no_summary
        """
    )

    # ── Input: single file OR entire results directory ────────────────────────
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        "--input",
        metavar="PATH",
        help="Path to a single *_markdown_bbox.json file"
    )
    input_group.add_argument(
        "--results_dir",
        metavar="DIR",
        help=(
            "Path to the results directory produced by nemotron_parse_pipeline.py\n"
            "Script auto-finds every *_markdown_bbox.json in any sub-folder\n"
            "and processes them one by one.\n\n"
            "Expected layout:\n"
            "  results_dir/\n"
            "  ├── Doc A/\n"
            "  │   └── Doc A_markdown_bbox.json\n"
            "  └── Doc B/\n"
            "      └── Doc B_markdown_bbox.json"
        )
    )

    # ── Optional flags ────────────────────────────────────────────────────────
    parser.add_argument(
        "--output_dir",
        default=None,
        metavar="DIR",
        help=(
            "Where to save the _structure.json files.\n"
            "Default: same folder as each input file (inside the doc sub-folder)."
        )
    )
    parser.add_argument(
        "--ollama_model",
        default=DEFAULT_OLLAMA_MODEL,
        metavar="MODEL",
        help=(
            f"Ollama model for summarisation (default: {DEFAULT_OLLAMA_MODEL})\n"
            "Examples: mistral, llama3, phi3, gemma, deepseek-r1"
        )
    )
    parser.add_argument(
        "--ollama_host",
        default=DEFAULT_OLLAMA_HOST,
        metavar="URL",
        help=f"Ollama server URL (default: {DEFAULT_OLLAMA_HOST})"
    )
    parser.add_argument(
        "--no_summary",
        action="store_true",
        help=(
            "Skip summary generation — build tree structure only.\n"
            "Useful for quick testing or when Ollama is not available."
        )
    )

    args = parser.parse_args()

    # ── Collect files to process ──────────────────────────────────────────────
    if args.input:
        files = [Path(args.input)]
    else:
        files = discover_bbox_files(args.results_dir)

    total = len(files)
    out_dir = Path(args.output_dir) if args.output_dir else None

    print(f"\n{'='*60}")
    print(f"  Build Hierarchy")
    print(f"  Files to process : {total}")
    print(f"  Ollama model     : {args.ollama_model}")
    print(f"  Summaries        : {'OFF (--no_summary)' if args.no_summary else 'ON'}")
    if out_dir:
        print(f"  Output dir       : {out_dir.resolve()}")
    else:
        print(f"  Output dir       : same folder as each input file")
    print(f"{'='*60}")

    # List all files that will be processed
    for i, f in enumerate(files, 1):
        print(f"  [{i}/{total}] {f.parent.name}/{f.name}")

    # ── Check Ollama once (shared across all files) ───────────────────────────
    ollama_ok = False
    if not args.no_summary:
        print(f"\n[→] Checking Ollama at {args.ollama_host} …")
        ollama_ok = _check_ollama(args.ollama_host, args.ollama_model)
        if ollama_ok:
            print(f"[✓] Ollama ready — model '{args.ollama_model}'\n")
        else:
            print(f"[WARN] Ollama unavailable — summaries will be raw text (500 chars)\n")

    # ── Process each file ─────────────────────────────────────────────────────
    success_count = 0
    failed        = []

    for idx, json_path in enumerate(files, 1):
        print(f"\n{'─'*60}")
        print(f"  [{idx}/{total}]  {json_path.parent.name}")
        print(f"{'─'*60}")

        ok = process_one(
            json_path    = json_path,
            output_dir   = out_dir,
            ollama_host  = args.ollama_host,
            ollama_model = args.ollama_model,
            use_summary  = not args.no_summary,
            ollama_ok    = ollama_ok,
        )

        if ok:
            success_count += 1
        else:
            failed.append(json_path.parent.name)

    # ── Final summary ─────────────────────────────────────────────────────────
    print(f"\n{'#'*60}")
    print(f"  DONE")
    print(f"  Processed : {success_count} / {total} successfully")
    if failed:
        print(f"\n  Failed ({len(failed)}):")
        for name in failed:
            print(f"    ✗  {name}")
    print(f"{'#'*60}\n")